name: Build and release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WSL_VERSION: 5.15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: wsl-perf
      - name: Copy deb package
        run: docker run --rm -v $(pwd):/mnt -w /mnt wsl-perf cp /usr/src/perf.deb perf-${WSL_VERSION}-microsoft-standard-WSL2.deb
      - name: Upload deb package
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "VERSION=${WSL_VERSION}"
          gh release create v${WSL_VERSION} perf-${WSL_VERSION}-microsoft-standard-WSL2.deb -t v${WSL_VERSION} -n "perf ${WSL_VERSION} for WSL2"
